# TODO: create either a separate docker-compose for prod, or use profiles

services:
  frontend:
    container_name: trivia-party-fe
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    develop:
      watch:
        - action: sync
          path: frontend
          target: /app/frontend
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
  backend:
    container_name: trivia-party-be
    build:
      context: backend
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/trivia_party
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
  db:
    container_name: trivia-party-db
    image: postgres:latest
    restart: always
    ports:
      - "5433:5432" # Purposefully 5433, not 5432
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: trivia_party

volumes:
  pg-data: